ALTER TABLE immobili
    ADD COLUMN pannelli_solari BOOLEAN DEFAULT FALSE,
ADD COLUMN terrazza BOOLEAN DEFAULT FALSE,
ADD COLUMN riscaldamento_pavimento BOOLEAN DEFAULT FALSE,
ADD COLUMN giardino BOOLEAN DEFAULT FALSE,
ADD COLUMN piscina BOOLEAN DEFAULT FALSE,
ADD COLUMN impianto_allarme BOOLEAN DEFAULT FALSE,
ADD COLUMN aria_condizionata BOOLEAN DEFAULT FALSE,
ADD COLUMN vista_panoramica BOOLEAN DEFAULT FALSE,
ADD COLUMN ripostiglio BOOLEAN DEFAULT FALSE,
ADD COLUMN termoautonomo BOOLEAN DEFAULT FALSE,
ADD COLUMN porta_blindata BOOLEAN DEFAULT FALSE,
ADD COLUMN cappotto BOOLEAN DEFAULT FALSE,
ADD COLUMN cortile_privato BOOLEAN DEFAULT FALSE;